export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL';

export const USER_PRODUCTS_REQUEST = 'USER_PRODUCTS_REQUEST';
export const USER_PRODUCTS_SUCCESS = 'USER_PRODUCTS_SUCCESS';
export const USER_PRODUCTS_FAIL = 'USER_PRODUCTS_FAIL';

export const USER_FEEDBACKS_REQUEST = 'USER_FEEDBACKS_REQUEST';
export const USER_FEEDBACKS_SUCCESS = 'USER_FEEDBACKS_SUCCESS';
export const USER_FEEDBACKS_FAIL = 'USER_FEEDBACKS_FAIL';